spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patientmanage
    username: root
    password: 1234

  jpa:
    hibernate:
         ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.liquibase-changelog.xml
